name: Checking Your Cabin
on:
  push:
    branches:
      - checks

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node Environment
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Step 1
        run: |
          node .bit/tests/test.hello.js
          
      - name: Step 2
        run: |
          node .bit/tests/test2.hello.js
